name = "msigsx-it-report"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "npm ci && npm run build"

[env.production.vars]
NODE_VERSION = "18"
USE_NPM = "true"
NPM_FLAGS = "--legacy-peer-deps"

[env.preview.vars]
NODE_VERSION = "18"
USE_NPM = "true"
NPM_FLAGS = "--legacy-peer-deps"